# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GIT_DIFF_TREE: $(git diff-tree --no-commit-id --name-only -r HEAD | grep '.*.py')

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pylint sphinx
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with PyLint
      run: |
        echo ${{env.GIT_DIFF_TREE}}
        if [[ ${{env.GIT_DIFF_TREE}} ]]; then pylint ${{env.GIT_DIFF_TREE}}; fi
    - name: Generate sphinx documentation
      run: |
        sphinx-apidoc -o . index
        make html
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: _build/html
